CHUNK_SIZE = 1200
CHUNK_OVERLAP = 200
TOP_K = 4
ROUTING_CONFIDENCE_THRESHOLD = 0.70

EMBEDDING_MODEL_NAME = "sentence-transformers/all-MiniLM-L6-v2"

OCR_TRIGGER_MAX_CHARS = 20

PHI3_MODEL_PATH = "models/phi3.gguf"
CONTEXT_WINDOW = 2048
MAX_NEW_TOKENS = 512
TEMPERATURE = 0.1
